spring.application.name=L18-Auth2-demo

spring.security.oauth2.client.registration.github.client-id=Ov23liKvJivXsUUhzM1Q
spring.security.oauth2.client.registration.github.client-secret=d4fd8e97473e956cbcc9554346c36952df8db016

