spring.application.name=L11-Spring-JDBC-demo
db.url=jdbc:mysql://localhost:3306/prod_db
db.username=user1
db.password=Pass@123



# To Create Datasource
spring.datasource.url=jdbc:mysql://localhost:3306/prod_db
spring.datasource.username=user1
spring.datasource.password=Pass@123
spring.datasource.hikari.maximum-pool-size=20


product.query.find.by.id=SELECT * FROM product WHERE ID = :id
